Drop Ext4 from sm-plugins in xapi.conf
xcp-ng-rpms/xapi pull request #43
Opened 2023-07-31 09:40 UTC by benjamreis

2023-07-31 09:42 UTC, benjamreis commented
[Koji scratch build to v8.3-incoming](https://koji.xcp-ng.org/taskinfo?taskID=34953)

2023-07-31 12:43 UTC, gduperrey approved these changes

2023-07-31 16:08 UTC, Wescoeur requested changes

2023-07-31 16:08 UTC, Wescoeur commented on SPECS/xapi.spec
> +- Drop Ext4 from sm-plugins in xapi.conf
ext4 * :wink:

2023-08-01 12:35 UTC, Wescoeur approved these changes

2023-08-01 12:51 UTC, merged

2023-08-01 12:53 UTC, benjamreis commented
[Koji build to v8.3-incoming](https://koji.xcp-ng.org/taskinfo?taskID=34962)