Add Largeblock to sm-plugins whitelist in xapi.conf
xcp-ng-rpms/xapi pull request #58
Opened 2024-03-18 15:46 UTC by Nambrok

2024-03-18 15:52 UTC, Wescoeur approved these changes

2024-03-18 16:27 UTC, stormi commented
Looks good, but we'll probably merge only when all internal tests are done on the driver and/or we are ready to publish to users.

2024-03-19 06:50 UTC, benjamreis approved these changes

2024-04-18 12:39 UTC, ydirson approved these changes

2024-04-18 12:56 UTC, stormi requested changes

2024-04-18 13:18 UTC, stormi approved these changes

2024-04-18 14:18 UTC, merged

2024-04-18 14:18 UTC, stormi commented
Koji build to v8.3-incoming: http://koji.xcp-ng.org/taskinfo?taskID=51420